# Generated by Django 4.1.1 on 2022-09-20 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=100)),
                ('preco', models.FloatField(verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.produto')),
                ('memoria_ram', models.IntegerField()),
                ('armazenamento', models.IntegerField()),
                ('sistema_operacional', models.CharField(max_length=50)),
            ],
            bases=('core.produto',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.produto')),
                ('tamanho', models.IntegerField()),
                ('taxa_de_atualizacao', models.IntegerField()),
                ('resolucao', models.CharField(max_length=15)),
                ('tipo_de_tela', models.CharField(max_length=10)),
            ],
            bases=('core.produto',),
        ),
    ]
