# Generated by Django 4.1.1 on 2022-09-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('CAIXA', 'Caixa'), ('ESTOQUISTA', 'Estoquista'), ('GERENTE', 'Gerente'), ('TECNICO', 'Técnico')], max_length=100)),
                ('matricula', models.CharField(max_length=100)),
            ],
        ),
    ]
